@baseUrl = http://localhost:3000
@objectId = ObjectId("65db6726d0dd5ac7b3a7055d")

# Channels

# @name createChannel
POST {{baseUrl}}/channels/create
Content-Type: application/json

{
    "id": "aaaaaab1223d",
    "name": "channel12",
    "description": "channel1 description1",
    "type": "private",
    "creatorID": "id12",
    "workspaceID": "abc3",
    "members": [{
        "userID": "ObjectId(\"65db6726d0dd5ac7b3a7055d1\")",
        "joinedAt": "1000000000"
    }],
    "topic": "Dev FE",
    "bookmarks": [],
    "bookmarkFolders": []
}