import { MyRingingCall } from "@/components/meeting/ringing-call/MyRingingCall";
import StreamVideoProvider from "@/providers/StreamClientProvider";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function WorkspaceRootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StreamVideoProvider>
      {children}
      <MyRingingCall />
    </StreamVideoProvider>
  );
}
